### ISSUE TITLE
¿Los roles son distintos por aplicación?

### ISSUE THREAD

**Issue by juanedi** [juanedi/seginf-sims#1]

**Comment by leanahabedian** [comment]
Cuando vimos la unidad de este tema (no me acuerdo el nombre, creo q la 2), Rodolfo habia dicho q los roles eran por sujeto y no por objeto. No se si eso aplica siempre, pero en cuanto al enunciado no queda claro si el rol es de usuarios o de aplicaciones.

**Comment by juanedi** [comment]
Acá lo que estoy diciendo es si _el esquema_ de roles va a ser el mismo para todas las aplicaciones o si va a variar según la aplicacion. Pero una vez que está definido el esquema, los roles dentro de la aplicación se asignan a un usuario.

Estoy casi seguro que había dicho que los tipos de roles sí iban a variar dependiendo de la aplicación, pero confirmemos por las dudas antes de cerrar el issue.

**Comment by juanedi** [comment]
Respuesta de Rodolfo:
Sí, el esquema de roles varía por aplicación.
