### ISSUE TITLE
RMQ: Interacción con otras apps.

### ISSUE THREAD

**Issue by juanedi** [juanedi/seginf-sims#10]
Según lo que hablamos, cuando el sistema tiene que comunicar algo a las otras aplicaciones deja un mensaje en la cola de cada aplicación, y estas se encargarán de procesarlo cuando puedan.

Hay que tener en cuenta que una aplicación _usuaria_ no pueda leer mensajes de la cola de otras aplicaciones.

Estaría bueno ver si es fácil, cuando se da de alta una aplicación, crearle automáticamente un usuario/password de RMQ para que esta tenga acceso a su cola de mensajes.

Enc aso que no sea sencillo, nuestra interfaz de alta de aplicaciones puede tener como requisito que haya creado usuario y password de la aplicación, haciendo el proceso un poco más manual.

**Comment by leanahabedian** [comment]
Esta bien, si usamos la opcion automática vamos a tener q generar passwords al azar copadas. Nada de usar alguna x default. 
Leandro E. Nahabedian

-----Original Message-----
From: Juan Edi reply@reply.github.com
Date: Sat, 19 May 2012 01:56:33 
To: leanahabedian@hotmail.com
Subject: [seginf-sims] RMQ: Interacción con otras apps. (#10)

Según lo que hablamos, cuando el sistema tiene que comunicar algo a las otras aplicaciones deja un mensaje en la cola de cada aplicación, y estas se encargarán de procesarlo cuando puedan.

 Hay que tener en cuenta que una aplicación _usuaria_ no pueda leer mensajes de la cola de otras aplicaciones.

 Estaría bueno ver si es fácil, cuando se da de alta una aplicación, crearle automáticamente un usuario/password de RMQ para que esta tenga acceso a su cola de mensajes.

 Enc aso que no sea sencillo, nuestra interfaz de alta de aplicaciones puede tener como requisito que haya creado usuario y password de la aplicación, haciendo el proceso un poco más manual.

---

 Reply to this email directly or view it on GitHub:
 https://github.com/juanedi/seginf-sims/issues/10

**Comment by juanedi** [comment]
Por lo que ví desde el cliente no se pueden crear usuarios. Por ahora hagámoslo manualmente (se puede hacer via línea de comandos, pero hay una interfaz web de RMQ muy buena), no creo que esté mal.
Sería algo parecido a cargar los roles de las apps via phpmyadmin, que Rodolfo dijo que estaba ok.
