### ISSUE TITLE
Utilizar bootstrap para frontend.

### ISSUE THREAD

**Issue by juanedi** [juanedi/seginf-sims#11]
No sé ustedes qué tan cómodos estén con HTML/CSS. Yo en particular soy bastante malo.

Lo que hemos usado en el trabajo para aplicaciones internas más de una vez es Twitter Bootstrap, un CSS base bastante bonito y sencillo (y bien documentado) que podemos usar para las páginas.

Si les interesa: http://twitter.github.com/bootstrap/

Si alguno la tiene clara con estas cosas y lo quiere hacer a mano igual bienvenido sea :)

**Comment by leanahabedian** [comment]
Me parece buena opción, para q tenga lindos efectos y no perdamos tiempo en eso. Yo entiendo el código y puedo tocar cosas pero hacer el css desde 0 es jodido. 
Leandro E. Nahabedian

-----Original Message-----
From: Juan Edi reply@reply.github.com
Date: Sat, 19 May 2012 02:02:23 
To: leanahabedian@hotmail.com
Subject: [seginf-sims] Utilizar bootstrap para frontend. (#11)

No sé ustedes qué tan cómodos estén con HTML/CSS. Yo en particular soy bastante malo.

 Lo que hemos usado en el trabajo para aplicaciones internas más de una vez es Twitter Bootstrap, un CSS base bastante bonito y sencillo (y bien documentado) que podemos usar para las páginas.

 Si les interesa: http://twitter.github.com/bootstrap/

 Si alguno la tiene clara con estas cosas y lo quiere hacer a mano igual bienvenido sea :)

---

 Reply to this email directly or view it on GitHub:
 https://github.com/juanedi/seginf-sims/issues/11

**Comment by juanedi** [comment]
Hecho, se está usando en la base de el admin y demo-db y va como piña.
