### ISSUE TITLE
Criterios de complejidad de las contraseñas

### ISSUE THREAD

**Issue by juanedi** [juanedi/seginf-sims#12]
La consigna dice "desde el administrador de identidades, se deben poder establecer criterios de complejidad de las contraseñas, y políticas de vencimiento".

Se definió que hay un único usuario/password que se usan para todas las aplicaciones. Por lo cuál no podrían definirse distintos criterios de complejidad por cada aplicación.

Por otra parte: ¿cómo se manejan las passwords viejas cuando se cambia un criterio? ¿se invalidan todas y se requiere volver a generarlas?

**Comment by rfestini** [comment]
1-De acuerdo, un único criterio para todas las aplicaciones.
2-Pensemos cuales serían los criterios y vemos después que nos conviene
hacer ante cambios de criterios, sugiero los que se me ocurren:

1- Cantidad mínima de caracteres
2- Set de caracteres obligatorios (minúsculas, mayúsculas números...)
3- tiempo de validez
4- cantidad de reintentos antes de bloquearse
5- cantidad de veces que hay que esperar antes de repetir una clave (mejor
redactado  )
6- cantidad de cambios permitidos por período de tiempo

2012/5/22 Juan Edi <
reply@reply.github.com

**Comment by juanedi** [comment]
Ya se resolvió esto. SIMS guarda el hash encodeado en varios formatos.
