### ISSUE TITLE
Elegir motor de BBDD

### ISSUE THREAD

**Issue by juanedi** [juanedi/seginf-sims#9]

**Comment by juanedi** [comment]
Tal vez la opción "obvia" sea mysql.

No lo hablamos, pero play tiene muy buen soporte de Heroku. Si no lo conocen, Heroku es una plataforma "en la nube" para hostear aplicaciones, muy sencilla.

Se crean una aplicación, agregan un repo git nuevo, hacen "git push heroku" y automáticamente les despliega la última versión de la aplicación.

Si nos interesa usar Heroku iría por PostgreSQL, pero tampoco lo veo super necesario.

**Comment by leanahabedian** [comment]
yo lo hable con ruben. El prefiere postgreSQL y yo sinceramente no se que diferencias tienen. Así que creo que el viento va a favor del postgreSQL...

**Comment by juanedi** [comment]
Perfecto, usamos postgres para el administrador.
Tal vez estaría bueno que la aplicación demo use otro motor, para hacer énfasis en que el modo de guardar las passwords por cada app es independiente, pero se ve en el momento.
